env: "replenishment"

env_args:
  key: "replenishment_efficient_env-v0"
  map_name: "walmart1.sku100.3_stores.standard"
  n_agents: 100
  task_type: "walmart1.sku100.3_stores.standard"
  mode: train
  time_limit: 100
  reward: "reward2"
  